version: 2
jobs:
  tests:
    working_directory: ~/tdd-guilda
    docker:
      - image: circleci/node:10.5
    steps:
      - checkout

      - run:
          name: Instalar pacotes
          command: npm i

      - run:
          name: testes
          command: npm test

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - tests
